// Auto-generated from activity_sets.json  (activity_sets.json)
const activityTypeToEntitySet = {
  new_returncustomer: "new_returncustomers",
  socialactivity: "socialactivities",
  serviceappointment: "serviceappointments",
  new_takhfif: "new_takhfifs",
  incidentresolution: "incidentresolutions",
  new_sms: "new_smses",
  campaignresponse: "campaignresponses",
  new_peigirihesab: "new_peigirihesabs",
  fax: "faxes",
  letter: "letters",
  new_mosaedeh: "new_mosaedehs",
  new_dissatisfaction: "new_dissatisfactions",
  new_pilotfollowing: "new_pilotfollowings",
  opportunityclose: "opportunitycloses",
  appointment: "appointments",
  task: "tasks",
  quoteclose: "quotecloses",
  bulkoperation: "bulkoperations",
  new_downtrendcustomer: "new_downtrendcustomers",
  new_morakhasi: "new_morakhasis",
  phonecall: "phonecalls",
  new_urgentfollowup: "new_urgentfollowups",
  untrackedemail: "untrackedemails",
  new_carditinception: "new_carditinceptions",
  new_customerlostfollowup: "new_customerlostfollowups",
  new_receiptpaymentapproval: "new_receiptpaymentapprovals",
  campaignactivity: "campaignactivities",
  new_pardakht: "new_pardakhts",
  new_daryaft: "new_daryafts",
  new_testactivity: "new_testactivities",
  orderclose: "ordercloses",
  recurringappointmentmaster: "recurringappointmentmasters",
  new_assembly: "new_assemblies",
  email: "emails",
};
export default activityTypeToEntitySet;
